import { getEnv } from "../utils/get-env";

const appConfig = () => ({
  NODE_ENV: getEnv("NODE_ENV", "development"),
  PORT: getEnv("PORT", "5000"),
  BASE_PATH: getEnv("BASE_PATH", "/api"),

  MONGO_URI: getEnv("MONGO_URI"),

  CLERK_WEBHOOK_SECRET: getEnv("CLERK_WEBHOOK_SECRET"),
  CLERK_PUBLISHABLE_KEY: getEnv("CLERK_PUBLISHABLE_KEY"),
  CLERK_SECRET_KEY: getEnv("CLERK_SECRET_KEY"),

  SESSION_SECRET: getEnv("SESSION_SECRET"),
  SESSION_EXPIRES_IN: getEnv("SESSION_EXPIRES_IN"),

  FRONTEND_ORIGIN: getEnv("FRONTEND_ORIGIN", "localhost"),

  CLOUDINARY_CLOUD_NAME: getEnv("CLOUDINARY_CLOUD_NAME"),
  CLOUDINARY_API_KEY: getEnv("CLOUDINARY_API_KEY"),
  CLOUDINARY_API_SECRET: getEnv("CLOUDINARY_API_SECRET"),
  CLOUDINARY_URL: getEnv("CLOUDINARY_URL"),

  MORALIS_API_KEY: getEnv("MORALIS_API_KEY"),

  REDIS_HOST: getEnv("REDIS_HOST"),
  REDIS_PORT: getEnv("REDIS_PORT"),
  REDIS_PASSWORD: getEnv("REDIS_PASSWORD"),
  REDIS_DB: getEnv("REDIS_DB"),

  RESEND_API_KEY: getEnv("RESEND_API_KEY"),
});

export const config = appConfig();
